### ISSUE TITLE
Request: Separation of JSON library

### ISSUE THREAD

**Issue by stephenberry** [jafarlihi/cppq#1]
Your library looks neat. One downside I see is that it directly uses nlohmann::json. It would be nice if nlohmann::json was an optional dependency and if the main library just worked on std::string. This would allow various JSON libraries to be used or even other formats for messages.

You could require a `cppq::transform` struct, which you could define in another header. That would allow nlohmann::json to be entirely optional and another implementation could be added instead.

Something like:
```c++
struct transform
{
   template <class T>
   std::string operator()(T& payload) {
      nlohmann::json j = payload;
      return j.dump();
   }
};
```

You could then still have the exact same code:
```c++
cppq::Task NewEmailDeliveryTask(EmailDeliveryPayload payload) {
  nlohmann::json j = payload;
  return cppq::Task{TypeEmailDelivery, j, 10};
}
```

`cppq::Task` here would just call `transform` on the second argument.

`transform` could be a function, but a struct is probably the better long term approach for more flexibility.
You can just predeclare `struct transform;` in cppq.hpp so that the sequence of including headers doesn't matter.

You could automate receiving the message, but I think it would be simpler, cleaner, and more flexible to have the user parse the std::string returned to the client. It's not hard to call `nlohmann::json::parse(task.payload);`
This also gives the user control over how the message is parsed and when it is parsed.

Thanks for your work on this!

**Comment by cantrepro** [comment]
Thanks for your suggestion @stephenberry
Makes sense, I'll certainly look into implementing it soon!

**Comment by cantrepro** [comment]
Dependency on `nlohmann::json` was removed.
